/*
 * main.c file
 */

#include "AST/Util.h"
#include "AST/Expression.h"
#include <stdio.h>
#include <string.h>

// Defines varOrder which is a list of variables in order of
// appearance in args[1]
#include "Lexer/Track.h"

int b(int i) { return i ? 1 : 0; }

void usage(char* name) {
	printf("Usage: %s [EXPRESSION] [OPERATION]... \n"
	       "Analyse and optimise boolean expressions\n"
	       "\n"
	       "Operations (Completed in order):\n"
	       " -t, --truth-table\tCreate a truth table from the expression specified\n"
	       " -o, --optimise\t\tOptimise and output the expression provided\n"
	       "\n"
	       "If no operations are specified, a truth table is generated by default\n"
	       "\n"
	       "The expression provided should be a string containing the following:\n"
	       " Vars\tCharacters from a-z\n"
	       " !\tNot operator\n"
	       " .\tAnd operator\n"
	       " ->\tLogical implication\n"
	       "\n"
	       "Bash expansion will interfere with a number of expressions,\n"
	       "when specifying from a shell, surround with single quotes.\n",
	       name);
}

int main(int argc, char *args[])
{
    if (argc == 1) {
        usage(args[0]); 
	return 1;
    }

    for (int i = 1; i < argc; i++) {}

    // Generate AST
    SExpression *e = getAST(args[1]);

    int symbols[26];

    // Create bitmasks for each input symbol
    int numSymbols = strlen(varOrder);
    for (int i = 0; i < numSymbols; i++) {
	char var = varOrder[i] - 97;
	symbols[var] = (1 << (numSymbols - 1 - i));
    }
  
    // Print header
    for (int i = 0; i < numSymbols; i++) { printf("%c ", varOrder[i]); }
    printf("\n");

    // Generate truth table
    for (int i = 0; i < (1 << numSymbols); i++) {
	    int result = evaluate(e, i, symbols);
	
	    for (int s = 0; s < numSymbols; s++) {
		printf("%d ", b(i & symbols[varOrder[s]-97]));
	    }

	    printf("%d\n", result);
    }
	
    // Free memory
    deleteExpression(e);
    return 0;
}
